### PR TITLE
Update to Angular 13, rxjs 7.5, eslint instead of tslint and other npm updates

### PR DESCRIPTION
**Pull request by iwantwin**
build(packaging)!: Update to Angular 13, rxjs 7.5, eslint instead of tslint, and other updates to ensure no audit issues remain at this time

Since Angular 13 the Angular Package Format has changed a lot. This update aligns with this new Angular Package Format. Since tslint is no longer supported this update also switches over to eslint. Related code fixes are applied as well. Angular 13 now uses rxjs 7.5.3.

Versioning was also changed to make the major version align with Angulars major version.

BREAKING CHANGE: Only working with Angular 13+, to support lower versions of Angular use earlier versions of this package.

### CODE REVIEW

**Comment by iwantwin** [comment]
@riccardomariani I really need this library to support Angular 13 and the new Angular Package Format. I compile my angular code manually to be able to do some static code analysis and the current latest version is giving me some trouble because I need to switch between ESM and CommonJS modules. With this update those issues will be resolved.

I plan on contributing to this project to align with future versions of Angular as well. If you have any feedback or questions, don't hestitate to contact me.

**Comment by riccardomariani** [comment]
@iwantwin I'm so sorry, but unfortunately I don't have enough time now to continue to maintain and develop this library. 
I'll do my best to upgrade to the latest version. After that I'll move this project in an unsupported state.

**Comment by iwantwin** [comment]
Would you have any problem with it if I made a forked package and maintain that as a new public package in my company's namespace?

**Comment by riccardomariani** [comment]
No problem untill it's distributed with the MIT license or any other free to use license (no commercial license)

**Comment by riccardomariani** [comment]
What do you think if I change the README to warn users that the project development has been discontinued and they could use your project as a replacement if they want?

**Comment by iwantwin** [comment]
Sounds good :) I will close this pull request and create an issue when we have our project set up, so you can change the readme then :)

**Comment by riccardomariani** [comment]
Thank you

**Pull request closed without merging**
